
    create table atributo (
        nombre varchar(255) not null,
        valor varchar(255),
        primary key (nombre)
    );

    create table categoria (
        cuenta_id integer not null,
        id integer generated by default as identity,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        cuenta_id integer not null,
        id integer generated by default as identity,
        creado timestamp(6) not null,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255),
        sku varchar(255),
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_atributo (
        producto_id integer not null,
        atributo_nombre varchar(255) not null,
        primary key (producto_id, atributo_nombre)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id integer not null,
        primary key (categoria_id, producto_id)
    );

    create table relacion (
        id integer generated by default as identity,
        producto_destino_id integer not null,
        producto_origen_id integer not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_atributo 
       add constraint FK_producto_atributo_atributo 
       foreign key (atributo_nombre) 
       references atributo;

    alter table if exists producto_atributo 
       add constraint FK_producto_atributo_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relacion 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relacion 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;

    create table atributo (
        nombre varchar(255) not null,
        valor varchar(255),
        primary key (nombre)
    );

    create table categoria (
        cuenta_id integer not null,
        id integer generated by default as identity,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        cuenta_id integer not null,
        id integer generated by default as identity,
        creado timestamp(6) not null,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255),
        sku varchar(255),
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_atributo (
        producto_id integer not null,
        atributo_nombre varchar(255) not null,
        primary key (producto_id, atributo_nombre)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id integer not null,
        primary key (categoria_id, producto_id)
    );

    create table relacion (
        id integer generated by default as identity,
        producto_destino_id integer not null,
        producto_origen_id integer not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_atributo 
       add constraint FK_producto_atributo_atributo 
       foreign key (atributo_nombre) 
       references atributo;

    alter table if exists producto_atributo 
       add constraint FK_producto_atributo_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relacion 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relacion 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;

    create table atributo (
        nombre varchar(255) not null,
        valor varchar(255),
        primary key (nombre)
    );

    create table categoria (
        cuenta_id integer not null,
        id integer generated by default as identity,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        cuenta_id integer not null,
        id integer generated by default as identity,
        creado timestamp(6) not null,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255),
        sku varchar(255),
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_atributo (
        producto_id integer not null,
        atributo_nombre varchar(255) not null,
        primary key (producto_id, atributo_nombre)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id integer not null,
        primary key (categoria_id, producto_id)
    );

    create table relacion (
        id integer generated by default as identity,
        producto_destino_id integer not null,
        producto_origen_id integer not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_atributo 
       add constraint FK_producto_atributo_atributo 
       foreign key (atributo_nombre) 
       references atributo;

    alter table if exists producto_atributo 
       add constraint FK_producto_atributo_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relacion 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relacion 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;
