
    create table categorias (
        id integer not null,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        creado timestamp(6) not null,
        cuenta_id bigint not null,
        id bigint generated by default as identity,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255) not null,
        sku varchar(255) not null,
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id bigint not null,
        primary key (categoria_id, producto_id)
    );

    create table relaciones (
        id integer not null,
        producto_destino_id bigint not null,
        producto_origen_id bigint not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categorias;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;

    create table categorias (
        id integer not null,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        creado timestamp(6) not null,
        cuenta_id bigint not null,
        id bigint generated by default as identity,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255) not null,
        sku varchar(255) not null,
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id bigint not null,
        primary key (categoria_id, producto_id)
    );

    create table relaciones (
        id integer not null,
        producto_destino_id bigint not null,
        producto_origen_id bigint not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categorias;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;

    create table categorias (
        id integer not null,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        creado timestamp(6) not null,
        cuenta_id bigint not null,
        id bigint generated by default as identity,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255) not null,
        sku varchar(255) not null,
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id bigint not null,
        primary key (categoria_id, producto_id)
    );

    create table relaciones (
        id integer not null,
        producto_destino_id bigint not null,
        producto_origen_id bigint not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categorias;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;

    create table categorias (
        id integer not null,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        creado timestamp(6) not null,
        cuenta_id bigint not null,
        id bigint generated by default as identity,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255) not null,
        sku varchar(255) not null,
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id bigint not null,
        primary key (categoria_id, producto_id)
    );

    create table relaciones (
        id integer not null,
        producto_destino_id bigint not null,
        producto_origen_id bigint not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categorias;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;

    create table categorias (
        id integer not null,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        creado timestamp(6) not null,
        cuenta_id bigint not null,
        id bigint generated by default as identity,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255) not null,
        sku varchar(255) not null,
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id bigint not null,
        primary key (categoria_id, producto_id)
    );

    create table relaciones (
        id integer not null,
        producto_destino_id bigint not null,
        producto_origen_id bigint not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categorias;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;

    create table categorias (
        id integer not null,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    create table producto (
        creado timestamp(6) not null,
        cuenta_id bigint not null,
        id bigint generated by default as identity,
        modificado timestamp(6),
        gtin varchar(255) not null unique,
        miniatura varchar(255),
        nombre varchar(255) not null,
        sku varchar(255) not null,
        texto_corto varchar(255),
        primary key (id)
    );

    create table producto_categoria (
        categoria_id integer not null,
        producto_id bigint not null,
        primary key (categoria_id, producto_id)
    );

    create table relaciones (
        id integer not null,
        producto_destino_id bigint not null,
        producto_origen_id bigint not null,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_categoria 
       foreign key (categoria_id) 
       references categorias;

    alter table if exists producto_categoria 
       add constraint FK_producto_categoria_producto 
       foreign key (producto_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_destino_id) 
       references producto;

    alter table if exists relaciones 
       add constraint FK_PRODUCTO_RELACION 
       foreign key (producto_origen_id) 
       references producto;
